### PR TITLE
创建json格式数据集，方便非php用户直接使用

### PR DESCRIPTION
**Pull request by gyn7561**

### CODE REVIEW

**Comment by topzyh** [comment]
感谢分享，能把生成的代码一起分享下吗？

**Comment by gyn7561** [comment]
1.用chrome打开 https://github.com/topzyh/Identity_Address_DB/blob/master/idtoad.sql
2.打开chrome 控制台 
3.运行下面的代码即可转换
`    let list = document.querySelectorAll(".blob-code")
    let data = [];
    list.forEach((dom) => {
        var line = dom.innerText;
        if (line.startsWith("INSERT INTO `idtoad` VALUES (")) {
            var split = line.replace("INSERT INTO `idtoad` VALUES (", "").replace(");", "").split(",");
            data.push({
                id: JSON.parse(split[0]),
                provinceId: JSON.parse(split[1]),
                cityId: JSON.parse(split[2]),
                countyId: JSON.parse(split[3]),
                provinceName: split[4].replace(/\'/g, "").trim(),
                cityName: split[5].replace(/\'/g, "").trim(),
                countName: split[6].replace(/\'/g, "").trim(),
                status: JSON.parse(split[7])
            });
        }
    });
    console.log(data);
    console.log(JSON.stringify(data))`
image

**Comment by gyn7561** [comment]
代码换行了 ，重新贴下
let list = document.querySelectorAll(".blob-code")
    let data = [];
    list.forEach((dom) => {
        var line = dom.innerText;
        if (line.startsWith("INSERT INTO `idtoad` VALUES (")) {
            var split = line.replace("INSERT INTO `idtoad` VALUES (", "").replace(");", "").split(",");
            data.push({
                id: JSON.parse(split[0]),
                provinceId: JSON.parse(split[1]),
                cityId: JSON.parse(split[2]),
                countyId: JSON.parse(split[3]),
                provinceName: split[4].replace(/\'/g, "").trim(),
                cityName: split[5].replace(/\'/g, "").trim(),
                countName: split[6].replace(/\'/g, "").trim(),
                status: JSON.parse(split[7])
            });
        }
    });
    console.log(data);
    console.log(JSON.stringify(data))

**Comment by gyn7561** [comment]
@topzyh

**Comment by topzyh** [comment]
好哒，谢谢

**Pull request merged**
